# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 8) do

  create_table "algorithm_comparison_joins", :force => true do |t|
    t.integer  "algorithm_id"
    t.integer  "comparison_type_id"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "algorithms", :force => true do |t|
    t.string   "name"
    t.integer  "algorithm_comparison_join_id"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "beams", :force => true do |t|
    t.integer  "number"
    t.decimal  "value"
    t.integer  "plan_id"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "comparison_types", :force => true do |t|
    t.string   "name"
    t.integer  "algorithm_comparison_join_id"
    t.decimal  "tolerance"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "comparisons", :force => true do |t|
    t.decimal  "result"
    t.text     "comment"
    t.integer  "patient_id"
    t.integer  "user_id"
    t.integer  "comparison_type_id"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "patients", :force => true do |t|
    t.string   "name"
    t.string   "id_number"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "plans", :force => true do |t|
    t.integer  "algorithm_id"
    t.integer  "comparison_id"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "users", :force => true do |t|
    t.string   "name"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

end
